### ISSUE TITLE
Example cannot continuously get data

### ISSUE THREAD

**Issue by kashalls** [RocketLeagueStats/rls-api-nodejs#3]
When using the example, you cannot have code running down the line. After the first task completes, it returns there and does not move onto the next task. Code continues anyways.

Ex:

```
   rlsstats.getTiersData(function (status, data) {
        if (status == 200) {
            console.log("-- Tiers data:");
            console.log(data);
        }
    });
```
```
    rlsstats.getRankedLeaderboard(rls.rankedPlaylists.DUEL, function (status, data) {
        if (status == 200) {
            console.log(data)
        }
    });
```
It will get tiersData but forget to get RankedLeaderboard. This happens to any single task.

**Comment by AeonLucid** [comment]
Fixed in v1.0.2.

This was happening because the API returned status 429 (rate limit), which shouldn't happen anymore because of throttling.
